//! `cargo xtask docs`: regenerate, or check, every page the docs site
//! derives from the crates.
//!
//! Each generator returns the content a file should have. This module
//! compares and writes, so `--check` and regeneration can never disagree
//! about what "current" means. Nothing a generated page says is typed twice:
//! it comes from a crate's manifest and `[package.metadata.axiolid]`, its
//! `README.md`, its `CHANGELOG.md`, and the facade features that enable it.
//!
//! ## Internal split
//!
//! - `workspace.rs`: the publishable crates, read once from `cargo metadata`.
//! - `changelog.rs`: release sections of the per-crate changelogs, and the
//!   assembled `docs/reference/changelog.md`.
//! - `reference.rs`: one page per crate under `docs/reference/crates/`, and
//!   the index that groups them by layer.
//! - `facts.rs`: `docs/.vitepress/data/facts.json`, which builds the sidebar.
//! - `readme.rs`: a crate README's prose for its page, and the lint that
//!   keeps each README a crates.io page linking back here.
//!
//! The architecture crate map and dependency graph are regenerated here too,
//! from `architecture::render`, so one command refreshes every derived page.

mod changelog;
mod facts;
mod readme;
mod reference;
mod workspace;

use std::path::{Path, PathBuf};

use crate::architecture::render;
use workspace::Workspace;

type Result<T> = std::result::Result<T, String>;

/// Directories whose every file is generated. A file there that no generator
/// produced belongs to a crate that is gone or renamed, and is removed.
const MANAGED: &[&str] = &["docs/reference/crates"];

/// The published site, which every crate README links back to.
pub(crate) const SITE: &str = "https://axiolid.github.io/kernel";
const REPO: &str = "https://github.com/axiolid/kernel";

/// The banner every wholly generated page starts with. It is a YAML comment
/// in front matter, not an HTML comment: the site renders Markdown with
/// `html: false`, which would print an HTML comment as text.
pub(crate) const BANNER: &str = "---\n# Generated by `cargo xtask docs`. Do not edit: change the source it names and regenerate.\n---";

/// One generated file: where it lives and what it should contain.
struct Output {
    rel: String,
    /// `None` when the file does not exist yet.
    current: Option<String>,
    updated: String,
}

impl Output {
    fn new(workspace: &Workspace, rel: impl Into<String>, updated: String) -> Self {
        let rel = rel.into();
        let current = std::fs::read_to_string(workspace.root.join(&rel)).ok();
        Self {
            rel,
            current,
            updated,
        }
    }

    fn stale(&self) -> bool {
        self.current.as_deref() != Some(self.updated.as_str())
    }
}

pub fn run(check: bool) -> Result<()> {
    let workspace = Workspace::load()?;
    let mut outputs = vec![
        changelog::page(&workspace)?,
        facts::generate(&workspace)?,
        Output::new(
            &workspace,
            render::CRATE_MAP,
            render::crate_map_document(&workspace.architecture),
        ),
        Output::new(
            &workspace,
            render::DEPENDENCY_GRAPH,
            render::graph_document(&workspace.architecture),
        ),
    ];
    outputs.extend(reference::generate(&workspace)?);
    let lint = readme::problems(&workspace);

    let orphans = orphans(&workspace.root, &outputs);
    let stale: Vec<&Output> = outputs.iter().filter(|o| o.stale()).collect();
    if check {
        let mut problems: Vec<String> = stale
            .iter()
            .map(|o| format!("{} is stale; run `cargo xtask docs`", o.rel))
            .collect();
        problems.extend(orphans.iter().map(|p| {
            format!(
                "{} is no longer generated; run `cargo xtask docs`",
                relative(&workspace.root, p)
            )
        }));
        problems.extend(lint);
        if problems.is_empty() {
            println!("docs in sync ({} generated files)", outputs.len());
            return Ok(());
        }
        return Err(format!(
            "{} problem(s):\n  {}",
            problems.len(),
            problems.join("\n  ")
        ));
    }

    for output in &stale {
        let path = workspace.root.join(&output.rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|error| format!("create {}: {error}", parent.display()))?;
        }
        std::fs::write(&path, &output.updated)
            .map_err(|error| format!("write {}: {error}", output.rel))?;
        println!("updated {}", output.rel);
    }
    for orphan in &orphans {
        std::fs::remove_file(orphan)
            .map_err(|error| format!("remove {}: {error}", orphan.display()))?;
        println!("removed {}", relative(&workspace.root, orphan));
    }
    if stale.is_empty() && orphans.is_empty() {
        println!("docs already in sync ({} generated files)", outputs.len());
    }
    // Generation cannot fix a README; report it after writing what it can.
    if lint.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "{} README problem(s):\n  {}",
            lint.len(),
            lint.join("\n  ")
        ))
    }
}

/// Files in a managed directory that no generator produced.
fn orphans(root: &Path, outputs: &[Output]) -> Vec<PathBuf> {
    let mut out = Vec::new();
    for dir in MANAGED {
        let Ok(entries) = std::fs::read_dir(root.join(dir)) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() && !outputs.iter().any(|o| root.join(&o.rel) == path) {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}

fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}
