use super::model::{Architecture, Result};
use std::fmt::Write as _;
use std::fs;

pub const CRATE_MAP: &str = "docs/architecture/crate-map.md";
pub const DEPENDENCY_GRAPH: &str = "docs/architecture/dependency-graph.md";

pub fn list(architecture: &Architecture) -> String {
    let mut output = String::new();
    for package in architecture.packages.values() {
        let visibility = if package.public { "public" } else { "internal" };
        writeln!(
            output,
            "{:<27} {:<16} {:<28} {:<10} {}",
            package.name, package.layer, package.role, visibility, package.path
        )
        .expect("write to String");
    }
    output
}

pub fn graph(architecture: &Architecture) -> String {
    let mut output = String::from(
        "graph TD\n    accTitle: Axiolid internal package dependency graph\n    accDescr: Each arrow points from a package to another internal package it depends on.\n",
    );
    for package in architecture.packages.values() {
        writeln!(
            output,
            "    {}[\"{}\\n{}\"]",
            node_id(&package.name),
            package.name,
            package.role
        )
        .expect("write to String");
    }
    for package in architecture.packages.values() {
        for dependency in &package.actual_internal_dependencies {
            writeln!(
                output,
                "    {} --> {}",
                node_id(&package.name),
                node_id(dependency)
            )
            .expect("write to String");
        }
    }
    output
}

pub fn crate_map_document(architecture: &Architecture) -> String {
    let mut output = String::from(
        "---\n# Generated by `cargo xtask architecture docs`; do not edit manually.\n---\n\n# Axiolid crate map\n\nArchitecture metadata describes ownership, not runtime capability support. Capability claims require a trait implementation plus conformance evidence.\n\n| Package | Path | Layer | Role | Domain | Visibility | Allowed internal dependencies |\n| --- | --- | --- | --- | --- | --- | --- |\n",
    );
    for package in architecture.packages.values() {
        let dependencies = if package.allowed_internal_dependencies.is_empty() {
            "—".to_owned()
        } else {
            package
                .allowed_internal_dependencies
                .iter()
                .map(|name| format!("`{name}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let visibility = if package.public { "public" } else { "internal" };
        // A published crate has a generated reference page (`cargo xtask docs`).
        let name = if package.publish {
            format!("[`{0}`](/reference/crates/{0})", package.name)
        } else {
            format!("`{}`", package.name)
        };
        writeln!(
            output,
            "| {} | [`{}`](https://github.com/axiolid/kernel/tree/main/{}) | `{}` | `{}` | `{}` | {} | {} |",
            name,
            package.path,
            package.path,
            package.layer,
            package.role,
            package.domain,
            visibility,
            dependencies
        )
        .expect("write to String");
    }
    output.push_str("\nTemporary domains are explicit migration debt and must disappear when their responsibility split lands.\n");
    output
}

pub fn graph_document(architecture: &Architecture) -> String {
    format!(
        "---\n# Generated by `cargo xtask architecture docs`; do not edit manually.\n---\n\n# Axiolid dependency graph\n\nEdges point from a package to an internal package it depends on.\n\n```mermaid\n{}```\n",
        graph(architecture)
    )
}

pub fn write_docs(architecture: &Architecture) -> Result<()> {
    write(architecture, CRATE_MAP, &crate_map_document(architecture))?;
    write(
        architecture,
        DEPENDENCY_GRAPH,
        &graph_document(architecture),
    )?;
    Ok(())
}

pub fn check_docs(architecture: &Architecture) -> Result<()> {
    check_document(architecture, CRATE_MAP, &crate_map_document(architecture))?;
    check_document(
        architecture,
        DEPENDENCY_GRAPH,
        &graph_document(architecture),
    )?;
    Ok(())
}

fn write(architecture: &Architecture, relative: &str, content: &str) -> Result<()> {
    let path = architecture.root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("create {}: {error}", parent.display()))?;
    }
    fs::write(&path, content).map_err(|error| format!("write {}: {error}", path.display()))
}

fn check_document(architecture: &Architecture, relative: &str, expected: &str) -> Result<()> {
    let path = architecture.root.join(relative);
    let actual = fs::read_to_string(&path)
        .map_err(|_| format!("{relative} is missing; run `cargo xtask architecture docs`"))?;
    if actual == expected {
        Ok(())
    } else {
        Err(format!(
            "{relative} is stale; run `cargo xtask architecture docs`"
        ))
    }
}

fn node_id(package: &str) -> String {
    package.replace('-', "_")
}
