#!/usr/bin/env python3
"""Assemble docs/reference/changelog.md from every crate's own CHANGELOG.md.

Versions now diverge per crate (ADR 0067), so no single file lists every
release in order. This script does not replace docs/CHANGELOG.md, which stays
the hand-written narrative for workspace-wide events (breaking bumps, major
releases); it builds the crate-indexed companion the docs site needs once a
patch can ship for one crate without a corresponding workspace entry.

Output is grouped by crate, newest release first per crate, matching the
Keep-a-Changelog heading shape each crate file already uses. Committed to
source and checked for drift, the same pattern as
`cargo xtask architecture docs` / `architecture check`.

Run: python3 scripts/assemble-crate-changelogs.py [--check]
--check (default) fails if the generated file would change. --write applies it.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "reference" / "changelog.md"
MARKER = "<!-- Generated by `scripts/assemble-crate-changelogs.py`; do not edit manually. -->"

HEADING_RE = re.compile(r"(?m)^## \[([^\]]+)\] - (\d{4}-\d{2}-\d{2})\s*$")


def metadata() -> dict:
    result = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--no-deps", "--locked"],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return json.loads(result.stdout)


def publishable_crates() -> list[tuple[str, Path]]:
    """(name, changelog_path) for every publishable workspace crate, sorted."""
    data = metadata()
    members = set(data["workspace_members"])
    crates = []
    for package in data["packages"]:
        if package["id"] not in members or package.get("publish") == []:
            continue
        manifest = Path(package["manifest_path"])
        crates.append((package["name"], manifest.parent / "CHANGELOG.md"))
    return sorted(crates, key=lambda pair: pair[0])


def released_sections(text: str) -> list[tuple[str, str, str]]:
    """(version, date, body) for every dated heading, skipping Unreleased.

    Unreleased entries are excluded on purpose: this page is what a consumer
    reads to decide whether upgrading a specific crate version is worth it,
    and unreleased work is not yet a version they can depend on.
    """
    matches = list(HEADING_RE.finditer(text))
    sections = []
    for index, match in enumerate(matches):
        version, date = match.group(1), match.group(2)
        body_start = match.end()
        body_end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        sections.append((version, date, text[body_start:body_end].strip("\n")))
    return sections


def render(crates: list[tuple[str, Path]]) -> str:
    lines = [
        MARKER,
        "",
        "# Per-crate changelog",
        "",
        "Every publishable crate versions and publishes independently"
        " ([ADR 0067](/adr/0067-crates-version-independently)); this page"
        " collects each crate's own `CHANGELOG.md`, newest release first per"
        " crate. Workspace-wide narrative — breaking bumps and coordinated"
        " releases — stays in the [top-level changelog](/CHANGELOG).",
        "",
    ]
    any_release = False
    for name, changelog in crates:
        if not changelog.exists():
            continue
        text = changelog.read_text(encoding="utf-8")
        sections = released_sections(text)
        if not sections:
            continue
        any_release = True
        lines.append(f"## {name}")
        lines.append("")
        for version, date, body in sections:
            lines.append(f"### {version} - {date}")
            lines.append("")
            if body:
                lines.append(body)
                lines.append("")
        lines.append("")
    if not any_release:
        lines.append(
            "No crate has a dated release yet under independent versioning; "
            "every crate's history to date lives in the top-level changelog."
        )
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", default=True, help="fail on drift (default)")
    mode.add_argument("--write", action="store_true", help="write the generated file")
    args = parser.parse_args()

    crates = publishable_crates()
    generated = render(crates)

    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"ASSEMBLE_CHANGELOG=WRITE crates={len(crates)} -> {OUTPUT}")
        return 0

    if not OUTPUT.exists():
        print(f"ASSEMBLE_CHANGELOG=DRIFT {OUTPUT} does not exist; run with --write")
        return 1
    current = OUTPUT.read_text(encoding="utf-8")
    if current != generated:
        print(f"ASSEMBLE_CHANGELOG=DRIFT {OUTPUT} is stale; run with --write")
        return 1
    print(f"ASSEMBLE_CHANGELOG=OK crates={len(crates)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
